### ISSUE TITLE
Custom error reporters cause a server crash

### ISSUE THREAD

**Issue by haykam821** [NucleoidMC/nucleoid-extras#177]
Since `LAST_REPORT` is not guaranteed to contain an `Instant`, the `startInclusive` parameter passed to the `Duration.between` method may be null:

https://github.com/NucleoidMC/nucleoid-extras/blob/311cbbcf3418736471860abdb2c5e104103a5609/src/main/java/xyz/nucleoid/extras/error/ExtrasErrorReporter.java#L68-L69

A `null` parameter is not allowed, and the game crashes:

```
java.lang.NullPointerException: Cannot invoke "java.time.temporal.Temporal.until(java.time.temporal.Temporal, java.time.temporal.TemporalUnit)" because "startInclusive" is null
	at java.base/java.time.Duration.between(Duration.java:490)
	at xyz.nucleoid.extras.error.ExtrasErrorReporter.reportCustom(ExtrasErrorReporter.java:69)
	at net.minecraft.class_1297.localvar$znp000$nucleoid_extras$clampVelocity(class_1297.java:8423)
```

**Comment by haykam821** [comment]
This issue should be reopened, as #178 did not fully fix the issue. The exception is now thrown by the `Map#replace` method call, as `ConcurrentHashMap` does not support null keys:

```
java.lang.NullPointerException: Ticking entity
	at java.base/java.util.concurrent.ConcurrentHashMap.replace(ConcurrentHashMap.java:1562)
	at xyz.nucleoid.extras.error.ExtrasErrorReporter.reportCustom(ExtrasErrorReporter.java:77)
	at net.minecraft.class_1297.localvar$znp000$nucleoid_extras$clampVelocity(class_1297.java:8423)
```

**Comment by Gegy** [comment]
Fixed in https://github.com/NucleoidMC/nucleoid-extras/commit/a1c97720c0bb712726bafdbb75d60fd9ddf29f54
